MyTaskManager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("task-manager/", include("TaskManagerApp.urls")),
]

TaskManagerApp/urls.py
from django.urls import path
from . import views

app_name = "task_manager"
urlpatterns = [
    path("", views.index, name="index"),
    path("task<int:task_id>/", views.task_detail, name="task_detail"),
    path("all_tasks/", views.all_tasks, name="all_tasks"),
    path("create_task/", views.create_task, name="create_task"),
    path("toggle_task_done_<int:task_id>/", views.toggle_task_done, name="toggle_task_done"),
    path('delete_task_<int:task_id>/', views.delete_task, name='delete_task'),
]

TaskManagerApp/models.py
from django.db import models
from django.utils import timezone

class Task(models.Model):
    title = models.CharField(max_length=200, default="")
    text = models.CharField(max_length=500, default="")
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    due_date = models.DateTimeField("due date", null=True)
    is_done = models.BooleanField(default=False)
    def __str__(self):
        return """
task title: {}
task text: {}
is done: {}
""".format(self.title, self.text, self.is_done)

TaskManagerApp/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    due_date = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],  # This format must match the input's string
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',
            'step': 60,  # Increment of step in seconds (set to 60 for minute-wise selection)
            'class': 'input'  # Add a class for styling
        }),
    )
    text = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 6,
        'class': 'textarea'  # Use class instead of 'cols' and inline styles
    }))
    is_done = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'checkbox'}),
        label='Done',
        required=False
    )
    class Meta:
        model = Task
        fields = ['title', 'text', 'due_date', 'is_done']

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'input'})  # Apply consistent input class
        self.fields['is_done'].widget.attrs.update({'class': 'checkbox'})
        self.fields['is_done'].initial = False

TaskManagerApp/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from .models import Task
from .forms import TaskForm
from django.http import HttpResponseRedirect

def index(request):
    return redirect('task_manager:all_tasks')

def all_tasks(request):
    task_list = Task.objects.order_by("due_date")
    context = { "task_list": task_list } if task_list.exists() else {}
    return render(request, "TaskManagerApp/all_tasks.html", context)

def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_manager:all_tasks')
    else:
        form = TaskForm()

    return render(request, 'TaskManagerApp/create_task.html', {'form': form})

def task_detail(request, task_id):
    task = get_task_or_raise(task_id)
    return render(request, "TaskManagerApp/task_detail.html", {"task": task})

def toggle_task_done(request, task_id):
    task = get_task_or_raise(task_id)
    task.is_done = not task.is_done
    task.save()
    referer_url = request.META.get('HTTP_REFERER')
    return HttpResponseRedirect(referer_url)

def delete_task(request, task_id):
    task = get_task_or_raise(task_id)
    task.delete()
    return redirect('task_manager:all_tasks')

def get_task_or_raise(task_id):
    try:
        return Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        raise Http404("Task does not exist")

TaskManagerApp/templates/TaskManagerApp/all_tasks.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>All Tasks</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/global_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/task_list_styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    {% if task_list %}
    <h2>All tasks</h2>
        <div class="task-list">
            {% for task in task_list %}
                <a class="task-card" href="{% url 'task_manager:task_detail' task.id %}">
                    <h3>{{ task.title }}</h3>
                    <p>Due: {{ task.due_date }}</p>
                    <div class="task-actions">
                        <form method="post" action="{% url 'task_manager:toggle_task_done' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" id="is_done_{{ task.id }}" name="is_done" onchange="this.form.submit()" {% if task.is_done %}checked{% endif %}>
                            <label for="is_done_{{ task.id }}">Done</label>
                        </form>
                        <form method="post" action="{% url 'task_manager:delete_task' task.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-btn" title="Delete Task"><i class="fas fa-trash"></i></button>
                        </form>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <h2>No tasks at the moment.</h2>
    {% endif %}
    <a href="{% url 'task_manager:create_task' %}" class="new-task-button">+</a>
</body>
</html>

TaskManagerApp/templates/TaskManagerApp/create_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Task</title>
    <link rel="stylesheet" href="{% static 'css/create_task_styles.css' %}">
</head>
<body>
    <div class="form-container">
        <h1>Create New Task</h1>
        <form method="post">
            {% csrf_token %}
            <p>
                <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                {{ form.title }}
            </p>
            <p>
                <label for="{{ form.text.id_for_label }}">{{ form.text.label }}</label>
                {{ form.text }}
            </p>
            <p>
                <label for="{{ form.due_date.id_for_label }}">{{ form.due_date.label }}</label>
                {{ form.due_date }}
            </p>
            <p>
                {{ form.is_done }}
                <label for="{{ form.is_done.id_for_label }}">{{ form.is_done.label }}</label>
            </p>
            <button type="submit" class="btn">Create Task</button>
        </form>
    </div>
</body>
</html>

TaskManagerApp/templates/TaskManagerApp/task_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Task Detail - {{ task.title }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/global_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/task_detail_styles.css' %}">
</head>
<body>
    <div class="task-detail-container">
        <h1>{{ task.title }}</h1>
        <p>{{ task.text }}</p>
        <p>Created: {{ task.creation_date | date:"F j, Y" }}</p>
        <p>Due: {{ task.due_date | date:"F j, Y" }}</p>

        <div class="task-actions">
            <form method="post" action="{% url 'task_manager:toggle_task_done' task.id %}">
                {% csrf_token %}
                <label for="is_done_{{ task.id }}">Done:</label>
                <input type="checkbox" id="is_done_{{ task.id }}" name="is_done" onchange="this.form.submit()" {% if task.is_done %}checked{% endif %}>
            </form>
            <form method="post" action="{% url 'task_manager:delete_task' task.id %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="delete-btn" title="Delete Task"><i class="fas fa-trash"></i></button>
            </form>
        </div>
    </div>
</body>
</html>